<<<<<<< HEAD
# Deploy ASP.NET Core app to Azure Web App
name: Deploy Kitabika BookStore to Azure

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'kitabika-bookstore'
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore NuGet packages
      run: dotnet restore BookStore.sln

    - name: Build solution
      run: dotnet build BookStore.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test BookStore.sln --configuration Release --no-build --verbosity normal

    - name: Publish application
      run: dotnet publish BookStore.Web/BookStore.Web.csproj --configuration Release --no-build --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp-artifacts
        path: ./publish

  deploy:
    name: Deploy to Azure
    runs-on: windows-latest
    needs: build
    environment: production
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: webapp-artifacts
        path: ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3EFDACBCD4A54D1FA71736435D8AD724 }}
        package: ./publish
=======
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - kitabika-bookstore

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kitabika-bookstore'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3EFDACBCD4A54D1FA71736435D8AD724 }}
>>>>>>> cbb1866af5434d98ae58c9eb7025fd79e741a756
